package StateChangeLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myStateDiagram__BehaviorDescriptor = new StateDiagram__BehaviorDescriptor();
  private final BHDescriptor myState__BehaviorDescriptor = new State__BehaviorDescriptor();
  private final BHDescriptor myTransition__BehaviorDescriptor = new Transition__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myState__BehaviorDescriptor;
      case 1:
        return myStateDiagram__BehaviorDescriptor;
      case 2:
        return myTransition__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf269776b13f84556L, 0xb9ea9dcaab37b019L, 0x67cbbaac519b5044L), MetaIdFactory.conceptId(0xf269776b13f84556L, 0xb9ea9dcaab37b019L, 0x67cbbaac519b503eL), MetaIdFactory.conceptId(0xf269776b13f84556L, 0xb9ea9dcaab37b019L, 0x67cbbaac519b5052L)).seal();
}
