package StateChangeLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Condition = 1;
  public static final int State = 2;
  public static final int StateDiagram = 3;
  public static final int Transition = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf269776b13f84556L, 0xb9ea9dcaab37b019L);
    builder.put(0x67cbbaac519b504bL, Action);
    builder.put(0x67cbbaac519b5058L, Condition);
    builder.put(0x67cbbaac519b5044L, State);
    builder.put(0x67cbbaac519b503eL, StateDiagram);
    builder.put(0x67cbbaac519b5052L, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
