package StateChangeLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class quick_fix_for_too_short_transition_name_QuickFix extends QuickFix_Runtime {
  public quick_fix_for_too_short_transition_name_QuickFix() {
    super(new SNodePointer("r:9a987643-22e2-43dc-b7c5-4d6aec05286c(StateChangeLanguage.typesystem)", "7479276855445514999"));
  }
  public String getDescription(SNode node) {
    return "Quick fix transition name too short";
  }
  public void execute(SNode node) {
    SPropertyOperations.assign(((SNode) quick_fix_for_too_short_transition_name_QuickFix.this.getField("nodeTransition")[0]), PROPS.event$1sLU, "Default transition");
  }

  private static final class PROPS {
    /*package*/ static final SProperty event$1sLU = MetaAdapterFactory.getProperty(0xf269776b13f84556L, 0xb9ea9dcaab37b019L, 0x67cbbaac519b5052L, 0x67cbbaac519b5053L, "event");
  }
}
